### ISSUE TITLE
Conversion failed.

### ISSUE THREAD

**Issue by jsaade** [anam-hossain/phantommagick#3]
I have installed PhantomJS through composer then installed phatommagick.
No matter what I do (html, source, to pdf, jpg, png, etc.) I always get 'Conversion failed'

How can I check the cause of the problem?
The download from composer downloaded the linux version, I manually downloaded the mac-os bin and replaced it.
The bin runs from terminal. But using phantommagic it always gives 'Conversion Failed'

**Comment by jsaade** [comment]
Seems a mac osx bug (yosemite) bug fix for binary here:
https://github.com/eugene1g/phantomjs/releases

**Comment by anam-hossain** [comment]
@jsaade <a href="https://github.com/anam-hossain/phantomjs-linux-x86-binary">anam-hossain/phantomjs-linux-x86-binary</a> binary is only for the Linux. Copy and paste binary will not work as it will not execute due to insufficient permission. 

You can try other Phantomjs installer:

https://github.com/jakoch/phantomjs-installer

I think, Phantomjs v2.00 has some issue when installed in a Mac system. So, try to install version 1.9.8.
```json
{
    "require": {
        "jakoch/phantomjs-installer": "1.9.8"
    },
    "config": {
        "bin-dir": "bin"
    },
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    }
}
```

Then all you have to do is set the Phantomjs binary path:

https://github.com/anam-hossain/phantommagick#binary

**Comment by jsaade** [comment]
The fix was to download the yosemite bin directly from https://github.com/eugene1g/phantomjs/releases
