### ISSUE TITLE
Protected Routes generate login page

### ISSUE THREAD

**Issue by jaredmeakin** [anam-hossain/phantommagick#9]
Hi @anam-hossain,

I'm using Laravel 5.2.10.

When attempting to use the converter, to generate a PDF, of a route protected by 'auth' I encounter errors. Specifically, the output PDF does not contain the view, but rather the login page.

Is there a fluent method I can chain onto my instantiation of converter, or some other way I can get authenticate prior to hitting the route?

Thanks! - Jared

**Comment by anam-hossain** [comment]
@jaredmeakin PhantomJS uses their own WebKit to process the HTTP request and the Laravel session is not available in command line. So, the authentication will fail when the route hit through PhantomJS.

However, I can suggest you one method to get around this. Instead of the passing a secure route to PhantomMagick, you can generate the view in a controller. This will allow you to verify an authenticated user.

```php
public function download(User $user)
{
  // Render view in controller
   $html =  View::make('invoices.payment', compact('user'))->render();

   $conv = new Converter();
   $conv->addPage($html)
    ->save('/your/destination/path/invoice.pdf');
}
```
The above operation will generate raw html. so it has some limitation.

> PhantomMagick only supports HTML and data can be provided via an URL or from the local disk. If you need to use raw HTML data, you can use multipage PDF conversion. However raw data does have some limitations; it does not support relative paths and it only supports inline styles and internal CSS.

More details:
https://github.com/anam-hossain/phantommagick#data-source

**Comment by jaredmeakin** [comment]
Thanks for your quick reply and guidance. I tried, but wasn't successful in getting it to work through a rendered view.

In the end I worked around the issue by creating a custom 'auth' middleware. Since the Converter call is originating from a Beanstalkd queue, fired by an Event/Listener, I was able to simply validate that the originating IP matched the host. Thus, protecting the route, and allowing the queue to access the view.

Love the package. Thanks so much!
